# Generated by Django 2.0.4 on 2019-11-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name_plural': '优惠券',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='MyCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('expiration_time', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(3, '已过期'), (2, '已使用'), (1, '未使用')])),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name_plural': '我的优惠卷',
                'db_table': 'mycoupon',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=191)),
                ('code', models.CharField(max_length=11)),
                ('coach', models.CharField(max_length=128)),
                ('is_coupon', models.BooleanField(default=False)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=7)),
                ('course', models.ForeignKey(on_delete=True, to='course.Course')),
                ('mycoupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.MyCoupon')),
                ('user', models.ForeignKey(on_delete=True, to='user.User')),
            ],
            options={
                'verbose_name_plural': '订单表',
                'db_table': 'orders',
            },
        ),
    ]
