# Generated by Django 2.1.4 on 2019-11-10 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_auto_20191110_1945'),
        ('course', '0007_auto_20191110_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Store')),
            ],
            options={
                'verbose_name_plural': '优惠券',
                'db_table': 'coupon',
            },
        ),
        migrations.CreateModel(
            name='MyCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('expiration_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name_plural': '我的优惠卷',
                'db_table': 'mycoupon',
            },
        ),
    ]
