# Generated by Django 2.1.4 on 2019-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycoupon',
            name='status',
            field=models.IntegerField(choices=[(3, '已过期'), (1, '未使用'), (2, '已使用')]),
        ),
    ]
