# Generated by Django 2.1.4 on 2019-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191112_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycoupon',
            name='status',
            field=models.IntegerField(choices=[(2, '已使用'), (1, '未使用'), (3, '已过期')]),
        ),
    ]
