# Generated by Django 2.1.4 on 2019-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191111_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='mycoupon',
            name='status',
            field=models.IntegerField(choices=[(2, '已使用'), (1, '未使用'), (3, '已过期')]),
        ),
    ]
