# Generated by Django 2.0.4 on 2019-11-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191112_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='store',
        ),
        migrations.AddField(
            model_name='coupon',
            name='money',
            field=models.DecimalField(decimal_places=2, default='', max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mycoupon',
            name='status',
            field=models.IntegerField(choices=[(2, '已使用'), (3, '已过期'), (1, '未使用')]),
        ),
    ]
