# Generated by Django 2.1.4 on 2019-11-11 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191111_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='store',
        ),
        migrations.RemoveField(
            model_name='mycoupon',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='mycoupon',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='MyCoupon',
        ),
    ]
