# Generated by Django 2.0.4 on 2019-11-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('cityname', models.CharField(max_length=128)),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('money_one', models.DecimalField(decimal_places=2, max_digits=7)),
                ('money_two', models.IntegerField()),
                ('pay_type', models.BooleanField()),
                ('information', models.CharField(max_length=255)),
                ('store_name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.City')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Coach')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('send_time', models.IntegerField()),
            ],
            options={
                'db_table': 'coursetime',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'courseType',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='coursetime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseTime'),
        ),
        migrations.AddField(
            model_name='course',
            name='coursetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseType'),
        ),
    ]
