# Generated by Django 2.0.4 on 2019-11-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.BooleanField(choices=[(2, '现金支付'), (1, '课包支付')]),
        ),
    ]
