# Generated by Django 2.1.4 on 2019-11-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '444', 'verbose_name_plural': '444'},
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.IntegerField(choices=[(2, '女'), (1, '男')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(2, '未满'), (3, '已结束'), (4, '已预约'), (1, '人数已满')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.IntegerField(choices=[(2, '现金支付'), (1, '课包支付')]),
        ),
    ]
