# Generated by Django 2.1.4 on 2019-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191112_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(4, '已预约'), (1, '人数已满'), (2, '未满'), (3, '已结束')]),
        ),
    ]
