# Generated by Django 2.1.4 on 2019-11-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191108_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(2, '未满'), (4, '已预约'), (1, '人数已满'), (3, '已结束')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseDirection', verbose_name='课程方向'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.IntegerField(choices=[(1, '课包支付'), (2, '现金支付')]),
        ),
    ]
