# Generated by Django 2.0.4 on 2019-11-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191106_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='store_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
