# Generated by Django 2.0.4 on 2019-11-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191106_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(2, '未满'), (3, '已结束'), (1, '人数已满')], default=1),
            preserve_default=False,
        ),
    ]
