# Generated by Django 2.0.4 on 2019-11-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_coursestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(1, '人数已满'), (3, '已结束'), (2, '未满')]),
        ),
    ]
