# Generated by Django 2.1.4 on 2019-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20191108_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': '教练表', 'verbose_name_plural': '教练表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='coursetype',
            options={'verbose_name': '课程分类', 'verbose_name_plural': '课程分类'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '城市表', 'verbose_name_plural': '城市表'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '店铺表', 'verbose_name_plural': '店铺表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(3, '已结束'), (2, '未满'), (1, '人数已满'), (4, '已预约')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.IntegerField(choices=[(2, '现金支付'), (1, '课包支付')]),
        ),
    ]
