# Generated by Django 2.0.4 on 2019-11-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191106_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_ntroduction', models.CharField(max_length=255)),
                ('training_effect', models.CharField(max_length=255)),
                ('crowd', models.CharField(max_length=255)),
                ('FQA', models.CharField(max_length=255)),
                ('notice', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'coursedetail',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('pid', models.IntegerField()),
                ('sname', models.CharField(max_length=128)),
                ('level', models.IntegerField()),
                ('citycode', models.CharField(blank=True, max_length=128, null=True)),
                ('yzcode', models.CharField(blank=True, max_length=128, null=True)),
                ('mername', models.CharField(max_length=128)),
                ('Lng', models.FloatField()),
                ('Lat', models.FloatField()),
                ('pinyin', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(4, '已预约'), (2, '未满'), (3, '已结束'), (1, '人数已满')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.BooleanField(choices=[(1, '课包支付'), (2, '现金支付')]),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='course',
            field=models.ForeignKey(on_delete=True, to='course.Course'),
        ),
    ]
