# Generated by Django 2.0.4 on 2019-11-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191112_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.IntegerField(choices=[(2, '女'), (1, '男')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(3, '已结束'), (4, '已预约'), (1, '人数已满'), (2, '未满')]),
        ),
    ]
