# Generated by Django 2.1.4 on 2019-11-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191108_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedirection',
            options={'verbose_name': '课程方向表', 'verbose_name_plural': '课程方向表'},
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.IntegerField(choices=[(2, '女'), (1, '男')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(2, '未满'), (1, '人数已满'), (4, '已预约'), (3, '已结束')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.CourseDirection'),
        ),
    ]
