# Generated by Django 2.0.4 on 2019-11-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20191112_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(4, '已预约'), (2, '未满'), (1, '人数已满'), (3, '已结束')]),
        ),
    ]
