# Generated by Django 2.1.4 on 2019-11-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20191108_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(2, '未满'), (3, '已结束'), (1, '人数已满'), (4, '已预约')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.IntegerField(choices=[(1, '课包支付'), (2, '现金支付')]),
        ),
    ]
