# Generated by Django 2.0.4 on 2019-11-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20191107_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(2, '未满'), (3, '已结束'), (4, '已预约'), (1, '人数已满')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.BooleanField(choices=[(2, '现金支付'), (1, '课包支付')]),
        ),
    ]
