# Generated by Django 2.0.4 on 2019-11-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20191113_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(1, '人数已满'), (3, '已结束'), (4, '已预约'), (2, '未满')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.IntegerField(choices=[(1, '课包支付'), (2, '现金支付')]),
        ),
    ]
