# Generated by Django 2.1.4 on 2019-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20191108_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(3, '已结束'), (2, '未满'), (1, '人数已满'), (4, '已预约')]),
        ),
    ]
