# Generated by Django 2.0.4 on 2019-11-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20191107_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='address',
        ),
        migrations.RemoveField(
            model_name='course',
            name='information',
        ),
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Region'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(2, '未满'), (1, '人数已满'), (4, '已预约'), (3, '已结束')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.BooleanField(choices=[(1, '课包支付'), (2, '现金支付')]),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
