# Generated by Django 2.0.4 on 2019-11-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20191107_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(3, '已结束'), (2, '未满'), (1, '人数已满'), (4, '已预约')]),
        ),
    ]
