# Generated by Django 2.1.4 on 2019-11-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20191110_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.IntegerField(choices=[(2, '私教'), (1, '团教')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(2, '未满'), (1, '人数已满'), (4, '已预约'), (3, '已结束')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.IntegerField(choices=[(1, '课包支付'), (2, '现金支付')]),
        ),
    ]
