# Generated by Django 2.0.4 on 2019-11-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20191107_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetime',
            old_name='send_time',
            new_name='spend_time',
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(2, '未满'), (3, '已结束'), (1, '人数已满'), (4, '已预约')]),
        ),
    ]
