# Generated by Django 2.0.4 on 2019-11-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20191107_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(1, '人数已满'), (4, '已预约'), (3, '已结束'), (2, '未满')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.BooleanField(choices=[(2, '现金支付'), (1, '课包支付')]),
        ),
    ]
