# Generated by Django 2.1.4 on 2019-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20191111_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='coursestatus',
            field=models.IntegerField(choices=[(1, '人数已满'), (2, '未满'), (4, '已预约'), (3, '已结束')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='pay_type',
            field=models.IntegerField(choices=[(2, '现金支付'), (1, '课包支付')]),
        ),
    ]
