# Generated by Django 2.0.4 on 2019-11-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('openid', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128)),
                ('invitation_code', models.CharField(max_length=128)),
                ('invitation_num', models.IntegerField(default=0)),
                ('succeed_invitation', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')])),
                ('birthday', models.DateField()),
                ('tall', models.FloatField()),
                ('weight', models.FloatField()),
                ('BMI', models.FloatField()),
                ('aim_weight', models.FloatField()),
                ('hope', models.IntegerField(choices=[(1, '减脂塑性'), (2, '增肌塑形'), (3, '体态改善')])),
                ('day', models.IntegerField(choices=[(1, '2天'), (2, '3天'), (3, '4天'), (4, '5天')])),
                ('how_long', models.IntegerField(choices=[(3, '90分钟'), (2, '60分钟'), (1, '45分钟'), (4, '105分钟')])),
                ('tag', models.ManyToManyField(to='course.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name_plural': '用户信息计划表',
                'db_table': 'userinfor',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('height', models.CharField(blank=True, max_length=5, null=True)),
                ('weight', models.CharField(blank=True, max_length=5, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'userinformation',
            },
        ),
    ]
