# Generated by Django 2.1.4 on 2019-11-07 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('openid', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128)),
                ('invitation_code', models.CharField(max_length=128)),
                ('invitation_num', models.IntegerField(default=0)),
                ('succeed_invitation', models.IntegerField(default=0)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')])),
                ('birthday', models.DateField()),
                ('tall', models.FloatField()),
                ('weight', models.FloatField()),
                ('BMI', models.FloatField()),
                ('image', models.ImageField(upload_to='user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'userinfor',
            },
        ),
    ]
