# Generated by Django 2.1.4 on 2019-11-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20191112_1145'),
        ('user', '0003_auto_20191112_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='YuYUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=True, to='course.Course')),
                ('user', models.ForeignKey(on_delete=True, to='user.User')),
            ],
            options={
                'verbose_name_plural': '预约表',
                'db_table': 'yuyue',
            },
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='day',
            field=models.IntegerField(choices=[(2, '3天'), (4, '5天'), (1, '2天'), (3, '4天')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='hope',
            field=models.IntegerField(choices=[(3, '体态改善'), (2, '增肌塑形'), (1, '减脂塑性')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='how_long',
            field=models.IntegerField(choices=[(1, '45分钟'), (2, '60分钟'), (4, '105分钟'), (3, '90分钟')]),
        ),
    ]
