# Generated by Django 2.0.4 on 2019-11-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191106_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='gender',
            field=models.BooleanField(choices=[(2, '女'), (1, '男')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='gender',
            field=models.BooleanField(choices=[(2, '女'), (1, '男')]),
        ),
    ]
