# Generated by Django 2.0.4 on 2019-11-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191112_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='day',
            field=models.IntegerField(choices=[(1, '2天'), (3, '4天'), (2, '3天'), (4, '5天')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='gender',
            field=models.IntegerField(choices=[(2, '女'), (1, '男')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='hope',
            field=models.IntegerField(choices=[(1, '减脂塑性'), (2, '增肌塑形'), (3, '体态改善')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='how_long',
            field=models.IntegerField(choices=[(3, '90分钟'), (1, '45分钟'), (4, '105分钟'), (2, '60分钟')]),
        ),
    ]
