# Generated by Django 2.0.4 on 2019-11-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191112_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('weight', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'userinformation',
            },
        ),
        migrations.RemoveField(
            model_name='yuyue',
            name='course',
        ),
        migrations.RemoveField(
            model_name='yuyue',
            name='user',
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='day',
            field=models.IntegerField(choices=[(4, '5天'), (2, '3天'), (1, '2天'), (3, '4天')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='hope',
            field=models.IntegerField(choices=[(2, '增肌塑形'), (3, '体态改善'), (1, '减脂塑性')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='how_long',
            field=models.IntegerField(choices=[(4, '105分钟'), (1, '45分钟'), (2, '60分钟'), (3, '90分钟')]),
        ),
        migrations.DeleteModel(
            name='YuYUE',
        ),
    ]
