# Generated by Django 2.1.4 on 2019-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
    ]
