# Generated by Django 2.0.4 on 2019-11-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191113_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='day',
            field=models.IntegerField(choices=[(2, '3天'), (1, '2天'), (4, '5天'), (3, '4天')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='hope',
            field=models.IntegerField(choices=[(3, '体态改善'), (1, '减脂塑性'), (2, '增肌塑形')]),
        ),
        migrations.AlterField(
            model_name='userinfor',
            name='how_long',
            field=models.IntegerField(choices=[(4, '105分钟'), (1, '45分钟'), (3, '90分钟'), (2, '60分钟')]),
        ),
    ]
