# Generated by Django 2.1.4 on 2019-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191110_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='gender',
            field=models.IntegerField(choices=[(2, '女'), (1, '男')]),
        ),
    ]
