# Generated by Django 2.0.4 on 2019-11-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191107_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfor',
            name='img',
        ),
        migrations.AddField(
            model_name='userinfor',
            name='image',
            field=models.ImageField(default='', upload_to='user'),
            preserve_default=False,
        ),
    ]
