# Generated by Django 2.1.4 on 2019-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20191110_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
    ]
