# Generated by Django 2.1.4 on 2019-11-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191111_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfor',
            name='gender',
            field=models.IntegerField(choices=[(2, '女'), (1, '男')]),
        ),
    ]
